HeatMap/HeatMap/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from Interface.views import change_language
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('login/',auth_views.LoginView.as_view(template_name='./registration/login.html'),name='login'),
#     path('logout/',auth_views.LogoutView.as_view(template_name='./registration/logout.html'),name='logout'),
#     path('', include('Interface.urls')),
    
#     ]
urlpatterns = [
    path('change_language/', 
         change_language, 
         name='change_language')
]

urlpatterns+= i18n_patterns(
    path('fs_heatmap/', admin.site.urls),
    path('login/',auth_views.LoginView.as_view(template_name='./registration/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='./registration/logout.html'),name='logout'),
    path('', include('Interface.urls')),
    prefix_default_language=True
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HeatMap/Interface/urls.py
from django.urls import path
from .views import (
	                ChannelListView,
	                ChannelUpdateView,
	                ChannelDeleteView,
                    USBChannelUpdateView,
                    ZoneUpdateView,   
                               
	               )
from . import views

urlpatterns = [
    path('main/', views.generel, name='Interface-generelUi'),
    path('channel/', ChannelListView.as_view(), name='Interface-channel'),
    path('channel/<int:pk>/edit',ChannelUpdateView.as_view(), name='Interface-channel_edit'),
    path('channel/create',views.Home, name='Interface-new_channel'),
    path('channel/usb',views.createUSB, name='Interface-newUSBchannel'),
    path('channel/<int:pk>/usbedit',USBChannelUpdateView.as_view(), name='Interface-USBchanneledit'),
    path('channel/<int:pk>/delete',ChannelDeleteView.as_view(), name='Interface-channel_delete'),
    path('zone/<int:pk>/edit', ZoneUpdateView.as_view(), name='Interface-zone'),
    path('zoneedit/', views.ZoneeditData, name='Interface-zoneedit'),
    path('heatmap/', views.heatmap_page, name='Interface-heatmap'),
    path('displayLiveStream/', views.displayLiveStream, name='display-live-stream'),
    path('displayLiveStream/livestream/<int:id>/', views.liveStream_page, name='live-stream-page'),
    path('', views.Front, name='Interface-front'),
    
    # path('plivestream/', views.pauseLiveStream_page, name='pause-live-stream-page'),
    # path('pauseLivesStream/', views.pauseLiveStream, name='pause-live-stream'),

    
]

HeatMap/Interface/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm
from PIL import Image
from django.contrib.auth.hashers import make_password
# Create your models here.+


# Camera table
class Camera(models.Model):

    # rtsp_url = models.CharField(max_length=100)
    camera_model = models.CharField(max_length=40,unique=True)
    rtsp_url = models.ImageField(default='default.jpg', upload_to='images')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def channel(self):
        return Channel.objects.filter(camera=self)

    def __unicode__(self):
        return self.name


# Channel Table
class Channel(models.Model):
    username = models.CharField(max_length=128)
    password = models.CharField(max_length=128)
 #   IP = models.GenericIPAddressField(unique=True)
    IP = models.CharField(max_length=15, unique=True)
    portNum = models.CharField(max_length=5)
    cameraNum = models.CharField(max_length=3)
    description = models.CharField(max_length=255, unique=True)
    enabled = models.BooleanField(default=True)
  #  camera = models.ForeignKey(Camera, on_delete=models.CASCADE,related_name="cameras")
    camera = models.ForeignKey(
    Camera, related_name='channel_camera', on_delete=models.CASCADE)
    coordinates = models.CharField(max_length=1200, default='')
    names = models.CharField(max_length=600, default='')
    directions = models.CharField(max_length=600, default='')

    def save(self, *args, **kwargs):
        self.validate_unique()
        super(Channel, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('Interface-channel', kwargs={'pk': self.pk})


# Frame table
class Frame(models.Model):
    img_name = models.CharField(max_length=40)
    captureTime = models.DateTimeField()
    channel = models.ForeignKey(Channel, on_delete=models.CASCADE)

# HeatMap table
class Heatmap(models.Model):
    topColor = models.CharField(max_length=255, default='')
    bottomColor = models.CharField(max_length=255, default='')
    topLeftX = models.IntegerField(default=0)
    topLeftY = models.IntegerField(default=0)
    width = models.IntegerField(default=0)
    height = models.IntegerField(default=0)
    dwellingTime = models.IntegerField(default=-1)
    zoneArea = models.IntegerField(default=-1)
    frame = models.ForeignKey(Frame, on_delete=models.CASCADE)

# Direction table
class Direction(models.Model):
    topColor = models.CharField(max_length=255, default='')
    bottomColor = models.CharField(max_length=255, default='')
    topLeftX = models.IntegerField(default=0)
    topLeftY = models.IntegerField(default=0)
    width = models.IntegerField(default=0)
    height = models.IntegerField(default=0)
    direction = models.CharField(max_length=648)
    frame = models.ForeignKey(Frame, on_delete=models.CASCADE)

HeatMap/Interface/forms.py
from django import forms
from django.forms import ModelForm
from .models import Camera,Channel
from django.core.exceptions import ValidationError

  
       


class CameraForm(forms.ModelForm):
  class Meta:
    model = Camera
    fields = ['rtsp_url']

class ChannelEditForm(forms.ModelForm):
  class Meta:
    model = Channel
    camera = forms.ModelMultipleChoiceField(queryset=Camera.objects.all())
    fields = ['username','password','IP','portNum','cameraNum',
                  'description','enabled','camera','coordinates','names','directions']

  def clean(self):
    cleaned_data = super(ChannelEditForm,self).clean()
    return cleaned_data




class ChannelCreateForm(forms.ModelForm):

 #username = forms.CharField(error_messages={'required': _('No user name has been entered')}, max_length=128) 
  password = forms.CharField(widget=forms.PasswordInput)

  class Meta:
    model = Channel
    camera = forms.ModelMultipleChoiceField(queryset=Camera.objects.all())
    fields = ['username','password','IP','portNum','cameraNum',
                  'description','enabled','camera']
    widget = {
               'password' : forms.PasswordInput(),
             }

  
  def clean(self):
    cleaned_data = super(ChannelCreateForm,self).clean()
    return cleaned_data


class ListForm(forms.ModelForm):
  class Meta:
    model = Channel
    fields = ['IP','description','enabled']


class ChannelUSBForm(forms.ModelForm):
  #description = forms.CharField(max_length=255)
  #enabled = forms.BooleanField()

  class Meta:
    model = Channel
    fields = ['description','enabled']

  
  def clean(self):
    cleaned_data = super(ChannelUSBForm,self).clean()
    return cleaned_data



class USBchannelEditForm(forms.ModelForm):

  class Meta:
    model = Channel
    fields = ['description','enabled']

  def clean(self):
    cleaned_data = super(USBchannelEditForm,self).clean()
    return cleaned_data

class ZoneEdit(forms.ModelForm):

  class Meta:
    model = Channel
    fields = ['coordinates']
    

  def clean(self):
    cleaned_data = super(ZoneEdit,self).clean()
    return cleaned_data

        

HeatMap/Interface/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.template.loader import render_to_string
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, UpdateView, DeleteView
from django.views.generic.base import TemplateView
from django.views.generic.edit import ModelFormMixin
from django.urls import reverse_lazy
from django.conf import settings
from django.utils import timezone
from django.utils.translation import gettext as _
from django.views.decorators import gzip
from django.http import HttpResponse, StreamingHttpResponse
from django.http import HttpResponseRedirect
from django.forms import inlineformset_factory
from django.utils.translation import ugettext_lazy as _
from PIL import Image, ImageDraw
from shapely.geometry import Point, Polygon, box
from .forms import (ZoneEdit,
                    ListForm,
                    ChannelEditForm,
                    ChannelCreateForm,
                    ChannelUSBForm,
                    USBchannelEditForm,
                    CameraForm)
from .models import *
from django.contrib.auth.hashers import check_password
from threading import Thread
from collections import OrderedDict
from scipy.spatial import distance as dist
from imutils import paths
import imutils
import numpy as np
import os
import cv2
import threading
import time
import datetime
import json
import sys
import queue
import celery
import uuid
import dlib
# =====================================
from Interface.utils.trackableobject import *
from Interface.utils.centroidtracker import *
from Interface.utils.body import *
from Interface.utils.ColorRec import ForensicColorFrame
# ============================================================================

HEATMAP_MAX_DISAPPEARED = 5
COLOR_PALLETE = {"BLUE": (255, 0, 0), "TEAL": (255, 255, 0), "RED": (0, 0, 255),
                 "GREEN": (0, 255, 0), "YELLOW": (0, 255, 255), "PINK": (255, 110, 199), "DEFAULT": (0, 0, 0), "ORANGE": (34, 87, 255)}
global stop
stop = False
global stablize

lock = threading.Lock()
q = queue.Queue()

#Adjust cooridnates based on the scale between frame and canvas of frontend
def applyScale(a,x_scale,y_scale):
    b = a
    if(len(b)>0):
        for i in range(len(b)):
            b[i][0]= int(b[i][0]*x_scale)
            b[i][1]= int(b[i][1]*y_scale)
    return b

def applyDirectionScale(a,x_scale,y_scale):
    b = a
    if(len(b)>0):
        for j in range(len(b)):
            for item in b[j]:
                item[0] = int(item[0]*x_scale)
                item[1] = int(item[1]*y_scale)
    return b

def tuplefyItem(arrayOfArrays):
    return [tuple(item) for item in arrayOfArrays]

def genDirectDict(directions):
    direct_dict ={}
    total = len(directions)
    for item in directions:
        if item.direction in direct_dict:
            direct_dict[item.direction]+=1
        else:
            direct_dict[item.direction]=0
    for i in direct_dict:
        direct_dict[i]=direct_dict[i]/total
    return direct_dict


# Return list of start points rectangle
# startPoints of direction:origin==0
# endPoints of direction: origin ==1
def map_poly_directs(polygons, directions):
    result = {}
    zone = 0
    currentZone =0
    for poly in polygons:
        targetZone = Polygon(tuplefyItem(poly["points"]))
        for targeDirection in directions:
            targetPoint= Point(targeDirection[1])
            if(targetPoint.within(targetZone)):
                currentZone= zone
                result[currentZone]=targeDirection
        zone+=1

    return result



def genRect(directions, origin,width,height):
    # get all points into x , y list
    x = [point[origin][0] for point in directions]
    y = [point[origin][1] for point in directions]

    # take max and min values of x, y to construct
    # left-top, right-top, right-bottom, left-bottom coordinates
    minX, maxX, minY, maxY = min(x), max(x), min(y), max(y)
    minX = (minX-50, 0)[minX-50 < 0]
    maxX = (maxX+50, 700)[maxX+50 > width]
    minY = (minY-50, 0)[minY-50 < 0]
    maxY = (maxY+50, 500)[maxY+50 > height]

    leftTop = (minX, minY)
    rightTop = (maxX, minY)
    rightBottom = (maxX, maxY)
    leftBottom = (minX, maxY)
    return [leftTop, rightTop, rightBottom, leftBottom]

# Get direction'end points by direction 
def genEndPoints(directions):
    result = [tuple(point[1]) for point in directions]
    return result

# Return specific direction by entering the input of its end point
def getDirectionsByEnds(directions, endPoint):
    if direction and endpoint:
        for points in directions:
            if(points[1] == endPoint):
                return points

def distMap(frame1, frame2):
	"""outputs pythagorean distance between two frames"""
	frame1_32 = np.float32(frame1)
	frame2_32 = np.float32(frame2)
	diff32 = frame1_32 - frame2_32
	norm32 = np.sqrt(diff32[:,:,0]**2 + diff32[:,:,1]**2 + diff32[:,:,2]**2)/np.sqrt(255**2 + 255**2 + 255**2)
	dist = np.uint8(norm32*255)
	return dist

def saveDirection(id, link):

    target_dir = settings.MEDIA_ROOT + "/images/"+str(id)+"/"
    if (not os.path.isdir(target_dir)):
        os.makedirs(target_dir)
    # get default channel to save specific frame and heatmap
    defaultChannel = id
    # access global value stop to conrol thread if required
    global stop
    frame_counter = 0
    firstFrame = None
    ct = CentroidTracker(HEATMAP_MAX_DISAPPEARED)
    trackableObjects = {}
    trackers = []
    vid = cv2.VideoCapture(link)
    # define frame_height and frame_width
    # print("the video size is{} {}".format(width, height))
    
    # width 1280
    width= vid.get(3)
    # height 960
    height = vid.get(4) 
    x_scale = 700/width
    y_scale = 500/height 
    #load polygon coordinates data to array
    p = json.loads(Channel.objects.get(id=defaultChannel).coordinates)
    #load direction coordinates
    d = json.loads(Channel.objects.get(id=defaultChannel).directions)
    # generate dictionay contains zone index mapped to specific direction coorinates
    zone_direct_dictionary = map_poly_directs(p,d)
    #load polygon coordinates data to array
    targetPolygons = json.loads(Channel.objects.get(id=defaultChannel).coordinates)
    #load direction coordinates
    directions = json.loads(Channel.objects.get(id=defaultChannel).directions)
    # generate dictionay contains zone index mapped to specific direction coorinates

    print(str(zone_direct_dictionary))
    print("the original directions are------ "+str(directions))
    print("the startRect before adjustment---- "+str(genRect(directions,0,700,500)))
    #convert directions coordinates by applying actual scale on live streaming
    adjustedDirection = applyDirectionScale(directions,width/700,height/500)
    # generate targetStartRectangel
    # output -- [x0, x1,y1,y0]
    
    print("the adjust---- directions are---- "+str(adjustedDirection))
    print("the startGen after adj---- "+str(genRect(adjustedDirection,0,width,height)))
    # print("startRect before"+str(genRect(directions,0,700,500)))


    startRect = genRect(adjustedDirection, 0,width,height)
    # print("startRect after applying scale" + str(startRect))
    endRect = genRect(adjustedDirection, 1,width, height)
    xStartPoint,xEndPoint, yStartPoint, yEndPoint = startRect[0][0],startRect[1][0],startRect[3][0],startRect[2][1]
    
    

    
    #convert targetPolygon to the scale of detecting streaming
    adjustedTargetPolygons=targetPolygons
    for item in adjustedTargetPolygons:
        item["points"]=applyScale(item["points"],width/700,height/500)
    
    
    
    print("zone_direct_dictionary"+str(zone_direct_dictionary))
    
    while (not stop):
        ret, frame = vid.read()
        # initialize frame counter and firstFrame
        if ret == True:
            frame_counter += 1
            fresh_copy = frame.copy()
            fresh_copy2= frame.copy()
            recogFrame = frame.copy()
            frame_height = frame.shape[0]
            frame_width = frame.shape[1]
            
            if firstFrame is None:
                firstFrame = recogFrame
                frame1 = recogFrame
                frame2 = recogFrame  
                
            rows, cols, _ = np.shape(recogFrame)
            dist = distMap(frame1, recogFrame)
            frame1 = frame2
            frame2 = recogFrame                    
            
            rgb = cv2.cvtColor(recogFrame, cv2.COLOR_BGR2RGB)
            mod = cv2.GaussianBlur(dist, (9,9), 0)
            # apply thresholding
            #_, thresh = cv2.threshold(mod, 100, 255, 0)
            _, thresh = cv2.threshold(mod, 25, 255, 0)
            # calculate st dev test
            _, stDev = cv2.meanStdDev(mod)
            
            
            rects = []
            if frame_counter % 15 == 0:    
                if stDev > 2:
                    trackers = []
                    thresh = cv2.dilate(thresh, None, iterations=2)
                    cnts = cv2.findContours(
                        thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
                    cnts = imutils.grab_contours(cnts)
                    # loop over the contours
                    print("------------------cnts length------------------------  "+str(len(cnts)))
                    for c in cnts:
                        # Check Contour location
                        (xPoint, yPoint, wPoint, hPoint) = cv2.boundingRect(c)
                        yCenter = int((yPoint + (yPoint+hPoint)) / 2.0)
                        # if yCenter < int(round(H // 8)) or yCenter > int(round(H // 1.2)):
                        if yCenter < int(round(hPoint // 8)) or yCenter > int(round(hPoint // 1.2)):
                            # 100:
                            if cv2.contourArea(c) < 300 or cv2.contourArea(c) > 20000:
                                continue
                        else:

HeatMap/Interface/templates/Interface/channel.html
{% extends "Interface/base.html" %}
{% block content %}
{% load i18n %}
<section>
   <form enctype="multipart/form-data" action="" name="edit" method="" id="ChannelForm">
      {% csrf_token %}
      <div class="container add-channel">
         <a href="{% url 'Interface-new_channel' %}" class="btn btn-sm btn-outline-primary" type="submit">
            <b>
               <i class="mr-2 fas fa-plus-square"></i>
               {% get_current_language as LANGUAGE_CODE %}
               {% if LANGUAGE_CODE == 'en' %}
               Add Channel
               {%else%}
               Agregar Canal
               {%endif%}
            </b></a>

      </div>
      <div class="container">
         <table class="table" cellspacing="0">
            {% for channel in channels %}
            <tr>
               <!-- <td>{{ channel.id}} </td> -->
               {% if channel.IP %}
               <td> <b>IP Camera</b> </td>
               {% else %}
               <td> <b>USB Camera</b></td>
               {% endif %}
               <td><b>{{ channel.IP }} </b> </td>
               <td><b> {{ channel.description }} </b></td>

               <td>
                  {% if channel.IP %}
                  <a href="{% url 'Interface-channel_edit' channel.id %}" class="btn btn-sm btn-outline-success"
                     type="submit">
                     <i class="mr-2 fas fa-edit"></i>
                     {% get_current_language as LANGUAGE_CODE %}
                     {% if LANGUAGE_CODE == 'en' %}
                     edit
                     {%else%}
                     Editar
                     {%endif%}

                  </a>
                  {% else %}
                  <a href="{% url 'Interface-USBchanneledit' channel.id %}" class="btn btn-sm btn-outline-success"
                     type="submit">
                     <b>
                        <i class="mr-2 fas fa-edit"></i>

                        {% get_current_language as LANGUAGE_CODE %}
                        {% if LANGUAGE_CODE == 'en' %}
                        edit
                        {%else%}
                        Editar
                        {%endif%}
                     </b>
                  </a>
                  {% endif %}
               </td>

               <td>
                  <a href="{% url 'Interface-channel_delete' channel.id %}" class="btn btn-sm btn-outline-danger"
                     type="submit">
                     <b>
                        <i class="mr-2 fas fa-minus-square"></i>
                        {% get_current_language as LANGUAGE_CODE %}
                        {% if LANGUAGE_CODE == 'en' %}
                        Delete
                        {%else%}
                        Eliminar
                        {%endif%}
                     </b>
                     </button>
               </td>

               <td>
                  {% if channel.enabled == 1 %}  
                     <!-- <input type="checkbox" name="channel-enable" 
                        id="id_enabled" value="{{ channel.enabled.value }}" checked disabled> -->
                     <label class="text-success">
                        <b>
                           {% get_current_language as LANGUAGE_CODE %}
                           {% if LANGUAGE_CODE == 'en' %}
                           Enabled
                           {%else%}
                           Habilitar Canal
                           {%endif%}
                        </b>
                     </label>
                  {%else%}
                  <!-- <input type="checkbox" name="channel-enable"  id="id_enabled"
                     value="{{ channel.enabled.value }}" disabled> -->
                  <label class="text-danger">
                     <b>
                        {% get_current_language as LANGUAGE_CODE %}
                        {% if LANGUAGE_CODE == 'en' %}
                        Disabled
                        {%else%}
                        Habilitar Canal
                        {%endif%}
                     </b>
                  </label>
                  {% endif %}

               </td>
            </tr>
            {% endfor %}
         </table>
      </div>
   </form>
</section>
{% endblock content %}

HeatMap/Interface/templates/Interface/channel_create_success.html
{% extends "Interface/base.html" %}
{% block content %}
{% load i18n %}
<section>
    <div class="row justify-content-center">
        <div class="col-5">
       
                {% get_current_language as LANGUAGE_CODE %}
                             {% if LANGUAGE_CODE == 'en' %}
                             <p>The channel was succesfully Added!</p>
                             {%else%}
                             <p>Canal editado con éxito.</p>
                             {%endif%}
                
                <a href="{% url 'Interface-channel' %}" class="ml-0 btn btn-white wave-effect text-primary"
                     type="button">
                    {% if LANGUAGE_CODE == 'en' %}
                    Close
                    {%else%}
                    Cerrar
                    {%endif%}
                </a>
           
        </div>
    </div>

</section>
{% endblock content %}

HeatMap/Interface/templates/Interface/channel_delete.html
{% extends "Interface/base.html" %}
{% block content %}
{% load i18n %}
<div class="container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% get_current_language as LANGUAGE_CODE %}
        {% if LANGUAGE_CODE == 'en' %}
        <p>Are you sure you want to delete the channel: "{{ channels.id }}"</p>
        {%else%}
        <p>¿Está seguro que desea eliminar este canal "{{ channels.id }}" ? </p>
        {%endif%}


        <button class="btn btn-danger" type="submit">
            {% if LANGUAGE_CODE == 'en' %}
            Delete Channel
            {%else%}
            Eliminar Canal
            {%endif%}

        </button>
        <a href="{% url 'Interface-channel' %}" class="btn btn-primary" type="button">

            {% if LANGUAGE_CODE == 'en' %}
            Cancel
            {%else%}
            Cancelar
            {%endif%}
        </a>
    </form>
</div>
{% endblock content %}

HeatMap/Interface/templates/Interface/channel_edit.html
{% extends "Interface/base.html" %}
{% block content %}
{% load i18n %}

<section>
  <div class="row justify-content-center">
    <div class="col-5">
      <form enctype="multipart/form-data" class="needs-validation" action="" name="edit" method="POST"
        id="ChannelEditForm" novalidate>
        {% csrf_token %}
        {% get_current_language as LANGUAGE_CODE %}

        <div class="input-group">
          <div class="col-md-6 pl-0">
            <label for="username">
              {% if LANGUAGE_CODE == 'en' %}
              Username
              {%else%}
              Nombre de usuario
              {%endif%} </label>

            <input class="form-control" type="text" name="username" id="username" value="{{form.username.value}}"
              required>
            <div class="valid-feedback">
              Valid
            </div>
            <div class="invalid-feedback">
              Please choose a username.
            </div>
          </div>
          <div class="col-md-6 pr-0">
            <label>
              {% if LANGUAGE_CODE == 'en' %}
              Password
              {%else%}
              Contraseña
              {%endif%}
            </label>

            <input type="password" value="{{form.password.value}}" name="password" value="" class="form-control"
              maxlength="128" id="password" required>

            <div class="valid-feedback">
              Valid
            </div>
            <div class="invalid-feedback">
              Please enter a valid password.
            </div>
          </div>
        </div>
        <div class="form-row">
          <div class="col-md-4 pl-0 ">
            <label> {% if LANGUAGE_CODE == 'en' %}
              IP*
              {%else%}
              Dirección IP*
              {%endif%} </label>
            <input type="text" class="form-control" value="{{form.IP.value}}" name="IP" maxlength="128" id="IP"
              pattern="^(25[0-5]|2[0-4]\d|[0-1]?\d?[1-9]|[0-1]?[1-9][0])(\.(25[0-5]|2[0-4]\d|[0-1]?\d?\d)){3}$"
              required>

            <div class="valid-feedback">
              Valid
            </div>
            <div class="invalid-feedback">
              Please enter a valid IP
            </div>
          </div>
          <div class="col-md-4">
            <label>{% if LANGUAGE_CODE == 'en' %}
              Port Number
              {%else%}
              Número de puerto
              {%endif%} </label>
            <input class="form-control" value="{{form.portNum.value}}" type="text" name="portNum" maxlength="5"
              id="portNum" pattern="[1-99999]+" required>
          </div>
          <div class="col-md-4 pr-0">
            <label>{% if LANGUAGE_CODE == 'en' %}
              Camera Number
              {%else%}
              Número de la cámara
              {%endif%}</label>
            <input type="text" class="form-control" value="{{form.cameraNum.value}}" name="cameraNum" maxlength="5"
              id="cameraNum" pattern="[1-999]+" required>
          </div>
        </div>
        <div class="form-row">
          <label> {% if LANGUAGE_CODE == 'en' %}
            Camera Model
            {%else%}
            Modelo de la cámara
            {%endif%}</label>

          <select name="camera" class="custom-select" required id="id_camera_model">
            <!-- <option value="{{form.camera_id.value}}" selected> {{form.camera_id.value}}</option> -->
            {% for camera in cameras.all %}
            {% if camera.pk != form.camera.value%}
            <option value="{{camera.pk}}"> {{ camera.camera_model }}</option>

            {%else%}
            <option value="{{camera.pk}}" selected> {{ camera.camera_model }}</option>
            {% endif %}
            {% endfor %}
          </select>
        </div>
        
        
        <div class="form-row">
          <div class="col-md pl-0 pr-0">
            <label> {% if LANGUAGE_CODE == 'en' %}
              Description*
              {%else%}
              descripción*
              {%endif%}
            </label>
            <input type="text" class="form-control" value="{{form.description.value}}" name="description"
              maxlength="128" id="description" pattern="[a-zA-Z0-9\.\-_]+" required>
            <div class="valid-feedback">
              Valid
            </div>
            <div class="invalid-feedback">
              Please enter a valid description
            </div>
          </div>
          <!-- <div class="col-md-6 pr-0">
            <label>{% if LANGUAGE_CODE == 'en' %}
              Camera Usages:*
              {%else%}
              Usos de la cámara:*
              {%endif%}</label>
            <input class="form-control" value="{{form.usage.value}}" type="text"> -->
          <!-- </div> -->
        </div>

        <div>
          <!-- Default unchecked -->

          <label>Enabled</label>
          {%if form.enabled.value == 1%}
          <input type="checkbox" name="enabled" maxlength="5" id="enabled" checked>
          {%else%}

          <input type="checkbox" name="enabled" maxlength="5" id="enabled">
          {% endif %}
        </div>
        <div class="mt-3">
          <a href="{% url 'Interface-zone' channel.id %}" class="ml-0 btn btn-info" type="submit">
            {% if LANGUAGE_CODE == 'en' %}
            Select Zone area to grab
            {%else%}
            Seleccione el área o zona específica a utilizar
            {%endif%}

          </a><br>
          <small class="form-text">
            {% if LANGUAGE_CODE == 'en' %}
            Zone area used to grab the area for recongnition,the unselected area will be ignored
            {%else%}
            El área o zona específica seleccionada para establecer el área de reconocimiento. El área no seleccionada,
            será ignorada.
            {%endif%}

          </small>
        </div>
        <div>
          <a href="{% url 'Interface-channel' %}" class="ml-0 btn btn-white wave-effect text-primary" type="button">

            {% if LANGUAGE_CODE == 'en' %}
            Cancel
            {%else%}
            Cancelar
            {%endif%}
          </a>
          <button class="btn btn-primary" type="submit">
            {% if LANGUAGE_CODE == 'en' %}
            Update
            {%else%}
            Actualizar
            {%endif%}

          </button>
        </div>
      </form>
    </div>
  </div>

</section>


{% endblock content %}

HeatMap/Interface/templates/Interface/generel_Ui.html
{% extends "Interface/base.html" %}
{% block content %}


{% endblock content %}